baseURL = "http://localhost:1313/"
title = "H&W"
theme = "PaperMod"

enableRobotsTXT = true
enableEmoji = true
hasCJKLanguage = true
enableGitInfo = true

mainSections = ["post"]

[pagination]
  pagerSize = 5

defaultContentLanguage = "en"
languageCode = "en"

[languages.en]
  weight = 1
  label = "English"
  locale = "en"
  title = "H&W"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  categories = "/categories/:slug/"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "Tech"
  url = "/post/"
  weight = 10
[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 20
[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 30
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 40

[params]
  env = "production"
  description = "H&W tech blog"
  author = "hyyfrank"
  keywords = ["Hugo", "tech", "blog"]

  [params.label]
    text = "H&W"

  DateFormat = "2006-01-02"
  defaultTheme = "dark"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false

  [params.homeInfoParams]
    Title = "H&W"
    Content = "Tech notes and engineering blog"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/hyyfrank"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:hyyfrank@email.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "dracula"
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4

[minify]
  disableXML = true
  minifyOutput = true
