# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "http://hyyfrank.github.io/"
title = "H&W"
enableRobotsTXT = true
enableEmoji = true
theme = "hugo-theme-jane"
# theme = "go-hugo-theme"

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 3              # Number of articles displayed on the homepage  # 首页每页显示的文章数
rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name ↓        # 默认为下面配置的author.name ↓

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"           # Default language to use
[languages.en]
  languageCode = "en"

[author]                  # essential                     # 必需
  name = "hyyfrank"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# [[menu.main]]             # config your menu              # 配置目录
#   name = "Home"
#   weight = 10
#   identifier = "home"
#   url = "/"



[[menu.main]]
  name = "Tech"
  weight = 10
  identifier = "tech"
  url = "/tech/"
[[menu.main]]
  name = "Project"
  weight = 20
  identifier = "project"
  url = "/project/"
[[menu.main]]
  name = "Books"
  weight = 30
  identifier = "books"
  url = "/books/"
[[menu.main]]
  name = "Life"
  weight = 35
  identifier = "life"
  url = "/life/"
[[menu.main]]
  name = "Archives"
  weight = 40
  identifier = "archives"
  url = "/post/"
# [[menu.main]]
#   name = "Tags"
#   weight = 50
#   identifier = "tags"
#   url = "/tags/"


[params]
  since = "2012"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Otherwise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "F&W"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["Hugo", "theme","jane"]
  description = "Hugo theme jane example site."

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = false                                                                            # 是否开启目录
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = ['custom.css']            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['custom.js','anime.js']             # if ['custom.js'], load '/static/js/custom.js' file

  [params.social]                                         # 社交链接
    a-email = "mailto:your@email.com"
    b-stack-overflow = "http://hyyfrank.github.io"
    c-twitter = "http://hyyfrank.github.io"
    d-facebook = "http://hyyfrank.github.io"
    e-linkedin = "http://hyyfrank.github.io"
    f-google = "http://hyyfrank.github.io"
    g-github = "http://hyyfrank.github.io"
    h-weibo = "http://hyyfrank.github.io"
    i-zhihu = "http://hyyfrank.github.io"
    j-douban = "http://hyyfrank.github.io"
    k-pocket = "http://hyyfrank.github.io"
    l-tumblr = "http://hyyfrank.github.io"
    m-instagram = "http://hyyfrank.github.io"
    n-gitlab = "http://hyyfrank.github.io"
    o-goodreads = "http://hyyfrank.github.io"
    p-coding = "http://hyyfrank.github.io"
    q-bilibili = "http://hyyfrank.github.io"
    r-codeforces = "http://hyyfrank.github.io"
    s-mastodon = "http://hyyfrank.github.io"
    t-youtube = "http://hyyfrank.github.io"
    u-twitch = "http://hyyfrank.github.io"
